### ISSUE TITLE
[Epic] Prod-ready Setup Docs

### ISSUE THREAD

**Issue by blueridger** [sourcecred/docs#270]
- [ ] “Is SourceCred right for my community?”
- [ ] “Instance Set Up” (polishing)
- [ ] “How to configure your instance”
  - [ ] File-by-file, attribute-by-attribute documentation
  - [ ] The Case for Tithing
- [ ] “How to maintain your instance”
  - [ ] Ways to manage Identities (merge and activate)
  - [ ] Ways to do payouts
